### ISSUE TITLE
Fetching an ImageInstanceCollection on an empty project returns a 404 HTTP error

### ISSUE THREAD

**Issue by waliens** [Cytomine-ULiege/Cytomine-core-legacy#21]
Is it the expected behavior ? I would rather return an empty collection with 200 HTTP code.
The current behavior causes the python client to return False when fetching the collection with the `project` filter which is kind of cumbersome, as it has to be handled manually:

```python
image_collection = ImageInstanceCollection().fetch_with_filter("project", id_project)

if not image_collection:
  image_collection = ImageInstanceCollection()  # create empty object
```

**Comment by urubens** [comment]
Hi, no, it's not the expected behavior. If "an empty project" refers to an existing project you have access to but with no image, the current behavior is what you expect: an empty collection with 200 HTTP code.

The API call behind `ImageInstanceCollection` is

    https://_YOUR_INSTANCE_/api/project/${id_project}/imageinstance.json

You can try it in your browser to double check. Potential errors are:
* 401: you are not authenticated
* 403: you don't have rights to access the given project
* 404: the project does not exist

Are you sure the `id_project` you are using is a valid project ID ?

**Comment by waliens** [comment]
It was indeed not the project id. Don't know where I got this id, sorry for the inconvenience.
